chat/urls.py
from django.urls import path
from .views import InboxView, UserListsView, MessagesListView, signup
from django.contrib.auth import views as auth_views

app_name = 'chat'


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('', MessagesListView.as_view(), name='message_list'),
    path('meet/', UserListsView.as_view(), name='users_list'),
    path('inbox/<str:username>/', InboxView.as_view(), name='inbox'),
    path('login/', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='chat:message_list'), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('chat.urls')),
    path('admin/', admin.site.urls),
]

theme/templates/layouts/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="author" content="gr1nch">
	<meta name="description" content="Chat website">
	<meta name="keywords" content="chat, website, chat website">

	<!-- adding tailwindcss -->
	<link href="{% static "css/output.css" %}" rel="stylesheet">
	{% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
	<!-- font awesome -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />

	<title>Chats</title>
</head>

<!-- the head of the page  -->
<header class="flex flex-row sm:justify-between space-x-4 bg-black h-16">
	<a href="{% url 'chat:message_list' %}">
		<h3 class="text-center text-white py-5 px-10 text-4xl font-bold">
			Chats!
		</h3>
	</a>

	<!-- Registration and logout buttons-->
	<div class="flex flex-row justify-between items-center">
	{% if request.user.is_authenticated %}
	<a href="{% url 'chat:logout' %}" class="flex mr-4">
		<button type="button" class="inline-block
									px-6 py-2.5
									bg-red-600
									text-white
									font-medium
									text-xs
									leading-tight
									uppercase
									rounded
									shadow-md
									hover:bg-red-700
									hover:shadow-lg
									focus:bg-red-700
									focus:shadow-lg
									focus:outline-none
									focus:ring-0
									active:bg-red-800
									active:shadow-lg
									transition
									duration-150
									ease-in-out">
				Logout
		</button>
	</a>

	{% else %}
		<a href="{% url 'chat:signup' %}" class="flex mr-2">
			<button type="button" class="inline-block
										px-6
										py-2.5
										bg-blue-600
										text-white
										font-medium
										text-xs
										leading-tight
										uppercase
										rounded
										shadow-md
										hover:bg-blue-700
										hover:shadow-lg
										focus:bg-blue-700
										focus:shadow-lg
										focus:outline-none
										focus:ring-0
										active:bg-blue-800
										active:shadow-lg
										transition
										duration-150
										ease-in-out">
					Sign up!
			</button>
		</a>
		<a href="{% url 'chat:login' %}" class="flex mr-2">
			<button type="button" class="inline-block
											px-6
											py-2.5
											bg-green-500
											text-white
											font-medium
											text-xs
											leading-tight
											uppercase rounded
											shadow-md
											hover:bg-green-600
											hover:shadow-lg
											focus:bg-green-600
											focus:shadow-lg
											focus:outline-none
											focus:ring-0
											active:bg-green-700
											active:shadow-lg
											transition
											duration-150
											ease-in-out">
					Login
			</button>
		</a>
	{% endif %}
	</div>
	<!-- Registration and logout buttons end-->
</header>
<!-- head end  -->

<body>
	<!-- content  -->
	<div class="bg-green-500 mx-auto h-[100%] pr-40 pl-40">
		<!-- creating a flex for the inbox and the messages -->
		<div class="flex py-1 h-[600]">
			<!-- showing all contacts -->
			<div class="flex-auto w-[30%] h-96">
				<!-- the head -->
				<div class="flex flex-row justify-between bg-slate-900 h-12">
					<a href="{% url 'chat:message_list' %}">
						<h2 class="text-start text-white py-2 pb-1 px-5 text-2xl font-semibold font-sans">
							inbox
						</h2>
					</a>
					<!-- add button -->
					<div class="block justify-self-end px-5 py-2">
						<button class=" hover:bg-blue-700 text-white font-bold py-1 px-2 rounded-full"
							onclick="location.href='{% url 'chat:users_list' %}';">
							<i class="fas fa-plus"></i>
						</button>
					</div>
					<!-- add button end -->
				</div>
				<!-- head end -->

				<!-- the body -->
				<div class="flex flex-col flex-nowrap overflow-x-hidden overflow-y-scroll	 pt-1 bg-slate-50 h-[600px]">
					{% block contacts %}
					{% endblock%}
				</div>
				<!-- the body end -->

			</div>
			<!-- contacts end -->

			<!-- a container for the messages and chatting -->
			<div class="flex-auto w-3/4 h-96">
				<!-- message body -->
				{% block message %}
				{% endblock %}
				<!-- message body end -->

			</div>
			<!-- message and chatting end -->
		</div>
		<!-- flex end -->
	</div>
	<!-- content end  -->


</body>

</html>